# Generated by Django 4.2.6 on 2023-10-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipamento', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
