# Generated by Django 4.2.6 on 2023-10-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'managed': False},
        ),
    ]
