# Generated by Django 4.2.6 on 2023-10-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipamento',
            table='equipamento',
        ),
    ]
